#!/usr/bin/env python3
"""IAMRITA profile animation generator.

Outputs (to dist/, published on the `output` branch):
  rhythm.png - Coding Rhythm card (weekday bars + streak, real data).

(The classic Snake 1.0 SVGs are generated by the Platane/snk step
 in .github/workflows/profile-animations.yml into the same dist/.)

Data: GitHub GraphQL contributionsCollection (needs GITHUB_TOKEN),
      falls back to no-auth scrape of /users/<login>/contributions.
"""
import os
import re
import json
import datetime as dt

import requests
from PIL import Image, ImageDraw, ImageFont

USER = "iamrita-ai"
OUT_DIR = "dist"

# ---------- style ----------
BG = (13, 17, 23)
PANEL = (22, 27, 34)
PURPLE = (139, 92, 246)
CYAN = (103, 232, 249)
WHITE = (240, 246, 252)
DIM = (139, 148, 158)
GOLD = (255, 213, 79)
GREEN = (63, 185, 80)


def font(size: int):
    for p in ("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
              "/usr/share/fonts/TTF/DejaVuSans-Bold.ttf",
              "arialbd.ttf"):
        try:
            return ImageFont.truetype(p, size)
        except Exception:
            continue
    return ImageFont.load_default()


def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


# ---------- data ----------
def fetch_graphql(token: str):
    q = ('query{user(login:"%s"){contributionsCollection{'
         'contributionCalendar{totalContributions '
         'weeks{contributionDays{date contributionCount}}}}}}' % USER)
    r = requests.post("https://api.github.com/graphql",
                      headers={"Authorization": f"bearer {token}"},
                      json={"query": q}, timeout=25)
    r.raise_for_status()
    cal = r.json()["data"]["user"]["contributionsCollection"]["contributionCalendar"]
    weeks = [[(d["date"], d["contributionCount"]) for d in w["contributionDays"]]
             for w in cal["weeks"]]
    return weeks, cal["totalContributions"]


def fetch_scrape():
    today = dt.date.today()
    year_ago = today - dt.timedelta(days=370)
    url = (f"https://github.com/users/{USER}/contributions"
           f"?from={year_ago}&to={today}")
    html = requests.get(url, headers={"User-Agent": "Mozilla/5.0"},
                        timeout=25).text
    found = re.findall(r'data-date="(\d{4}-\d{2}-\d{2})"[^>]*?data-level="(\d)"', html)
    pseudo = {0: 0, 1: 1, 2: 4, 3: 7, 4: 12}
    days = sorted((d, pseudo[int(l)]) for d, l in found)
    weeks, cur = [], []
    for d, c in days:
        cur.append((d, c))
        if len(cur) == 7:
            weeks.append(cur)
            cur = []
    if cur:
        weeks.append(cur)
    return weeks, sum(c for _, c in days)


# ---------- rhythm card ----------
def base_canvas(w, h):
    img = Image.new("RGB", (w, h), BG)
    d = ImageDraw.Draw(img)
    d.rounded_rectangle([2, 2, w - 3, h - 3], radius=16, outline=PURPLE, width=2)
    return img, d


def make_rhythm(weeks, total):
    weekday_totals = [0] * 7
    best = 0
    active = 0
    flat = []
    for week in weeks:
        for datestr, c in week:
            d = dt.date.fromisoformat(datestr)
            if d > dt.date.today():
                continue
            flat.append((datestr, c))
            weekday_totals[d.weekday()] += c
            best = max(best, c)
            if c > 0:
                active += 1
    flat.sort()
    streak = 0
    for datestr, c in reversed(flat):
        if datestr == dt.date.today().isoformat() and c == 0:
            continue
        if c > 0:
            streak += 1
        else:
            break

    w, h = 780, 320
    img, d = base_canvas(w, h)
    d.text((30, 22), "CODING RHYTHM  -  REAL DATA, ZERO EMOTIONS",
           font=font(21), fill=WHITE)

    names = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
    bx0, bw, by1, bh_max = 50, 62, 218, 110
    mx = max(weekday_totals) or 1
    for i, (nm, v) in enumerate(zip(names, weekday_totals)):
        bh = max(6, int(bh_max * v / mx))
        x0 = bx0 + i * (bw + 34)
        col = lerp(PURPLE, CYAN, v / mx)
        d.rounded_rectangle([x0, by1 - bh, x0 + bw, by1], radius=8, fill=col)
        d.text((x0 + bw / 2, by1 - bh - 26), str(v), font=font(15),
               fill=WHITE, anchor="ma")
        d.text((x0 + bw / 2, by1 + 10), nm, font=font(14), fill=DIM, anchor="ma")

    stats = [("YEAR TOTAL", str(total), PURPLE),
             ("ACTIVE DAYS", str(active), CYAN),
             ("BEST DAY", str(best), GOLD),
             ("DAY STREAK", f"{streak} DAYS", GREEN)]
    sw = 168
    d.text((w - 30, 24), "auto-refresh", font=font(13), fill=DIM, anchor="ra")
    img.save(f"{OUT_DIR}/rhythm.png")
    canvas = Image.new("RGB", (w, h + 78), BG)
    canvas.paste(img, (0, 0))
    d2 = ImageDraw.Draw(canvas)
    d2.rounded_rectangle([2, 2, w - 3, h + 78 - 3], radius=16,
                         outline=PURPLE, width=2)
    for i, (label, val, col) in enumerate(stats):
        x0 = 30 + i * (sw + 12)
        y0 = h + 8
        d2.rounded_rectangle([x0, y0, x0 + sw, y0 + 58], radius=10,
                             fill=PANEL, outline=col, width=2)
        d2.text((x0 + sw / 2, y0 + 6), label, font=font(12), fill=DIM, anchor="ma")
        d2.text((x0 + sw / 2, y0 + 24), val, font=font(19), fill=WHITE, anchor="ma")
    canvas.save(f"{OUT_DIR}/rhythm.png")
    return {"total": total, "active": active, "best": best, "streak": streak,
            "weekdays": weekday_totals}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    token = os.environ.get("GITHUB_TOKEN", "")
    try:
        if not token:
            raise RuntimeError("no token")
        weeks, total = fetch_graphql(token)
        print(f"data: GraphQL OK, total={total}")
    except Exception as e:
        print(f"data: GraphQL failed ({e}), using scrape fallback")
        weeks, total = fetch_scrape()
        print(f"data: scrape OK, total={total}")

    info = make_rhythm(weeks, total)
    print("rhythm.png:", json.dumps(info))


if __name__ == "__main__":
    main()
